apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: kiran6177/tickets 
        env: 
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-svc:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwtsecret
                key: JWT_SECRET
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-svc
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3002
    targetPort: 3002

